version: '3'

services:
  catalog-db:
    image: yugabytedb/yugabyte:latest
    container_name: rtdl_catalog-db
    volumes:
      - ./rtdl-catalog-db_data:/home/yugabyte/yb_data
    command: ["bin/yugabyted", "start", "--base_dir=/home/yugabyte/yb_data", "--daemon=false"]
    ports:
      - 7000:7000
      - 9000:9000
      - 5433:5433
      - 9042:9042
    healthcheck:
        test: ["CMD", "yb-ts-cli", "--server_address=localhost", "is_server_ready"]
        interval: 10s
        timeout: 5s
        retries: 12

  catalog:
    build:
      context: ./catalog
    image: rtdl/rtdl-catalog:latest
    container_name: rtdl_catalog
    ports:
      - 9083:9083
    volumes:
      - ./catalog/scripts/entrypoint-run.sh:/entrypoint.sh
    entrypoint: sh -c "chown hive:hive /entrypoint.sh && chmod +x /entrypoint.sh && sh -c /entrypoint.sh"
    depends_on:
      catalog-db:
        condition: service_healthy
    links:
      - catalog-db
  
  # process:
  #   image: flink:1.14.2-java11
  #   container_name: rtdl_process
  #   ports:
  #   - 8081:8081
  #   depends_on:
  #     - catalog
  #   links:
  #     - catalog

  # ingest:
  #   build:
  #     context: ./ingest
  #   image: rtdl/rtdl-ingest:latest
  #   container_name: rtdl_ingest
  #   ports:
  #   - 8080:8080
  #   depends_on:
  #     - process
