version: '3'

services:
  rtdl-dremio:
    platform: linux/amd64
    image: dremio/dremio-oss
    container_name: rtdl_dremio-init
    volumes:
      - ./storage/dremio/data:/opt/dremio/data
      - ./storage/rtdl-data_store:/mnt/datastore 
    expose:
      - 9047
      - 31010
      - 45678
    ports:
      - 9047:9047
      - 31010:31010
      - 45678:45678
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:9047/apiv2/server_status"]
        interval: 10s
        timeout: 5s
        retries: 24

      
  create-admin:
    platform: linux/amd64
    image: curlimages/curl
    container_name: rtdl_create-dremio-admin
    user: root
    volumes:
      - ./dremio/scripts/entrypoint-init.sh:/entrypoint.sh
    entrypoint: 
      sh -c "chmod +x /entrypoint.sh && sh /entrypoint.sh"
    depends_on:
      rtdl-dremio:
        condition: service_healthy
