version: '3'

services:
  ##### Config Services - Start #####
  ### For YBDB - Start ###
  # rtdl-db:
  #   platform: linux/amd64
  #   image: yugabytedb/yugabyte:latest
  #   container_name: rtdl_rtdl-db
  #   volumes:
  #     - ./storage/rtdl-db_data:/home/yugabyte/yb_data
  #   command: ["bin/yugabyted", "start", "--base_dir=/home/yugabyte/yb_data", "--daemon=false"]
  #   expose:
  #     - 5433
  #   ports:
  #     - 5434:5433
  #   healthcheck:
  #       test: ["CMD", "yb-ts-cli", "--server_address=localhost", "is_server_ready"]
  #       interval: 10s
  #       timeout: 5s
  #       retries: 12
  
  # rtdl-db-init:
  #   platform: linux/amd64
  #   image: rtdl/psql-client:latest
  #   container_name: rtdl_rtdl-db-init
  #   volumes:
  #     - ./config/scripts/rtdl-create-user-db.sql:/rtdl-create-user-db.sql
  #   entrypoint: psql -h rtdl-db -p 5433 -U yugabyte -f /rtdl-create-user-db.sql
  #   deploy:
  #     restart_policy:
  #       condition: on-failure
  #       delay: 5s
  #       max_attempts: 5
  #       window: 10s
  #   depends_on:
  #     rtdl-db:
  #       condition: service_healthy
  ### For YBDB - End ###

  ### For Postgres - Start ###
  rtdl-db:
    platform: linux/amd64
    image: postgres:latest
    container_name: rtdl_rtdl-db
    volumes:
      - ./storage/rtdl-db_data:/var/lib/postgresql/data
    expose:
      - 5432
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
        test: ["CMD-SHELL", "pg_isready -U postgres"]
        interval: 10s
        timeout: 5s
        retries: 12
  
  rtdl-db-init:
    platform: linux/amd64
    image: rtdl/psql-client:latest
    container_name: rtdl_rtdl-db-init
    volumes:
      - ./config/scripts/rtdl-create-user-db.sql:/rtdl-create-user-db.sql
    entrypoint: psql -h rtdl-db -p 5432 -U postgres -f /rtdl-create-user-db.sql
    environment:
      PGPASSWORD: postgres
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 5
        window: 10s
    depends_on:
      rtdl-db:
        condition: service_healthy
  ### For Postgres - End ###
  ##### Config Services - End #####


  ##### Catalog Services - Start #####
  ### For YBDB - Start ###
  # catalog-db:
  #   platform: linux/amd64
  #   image: yugabytedb/yugabyte:latest
  #   container_name: rtdl_catalog-db
  #   volumes:
  #     - ./storage/rtdl-catalog-db_data:/home/yugabyte/yb_data
  #   command: ["bin/yugabyted", "start", "--base_dir=/home/yugabyte/yb_data", "--daemon=false"]
  #   expose:
  #     - 5433
  #   ports:
  #     - 5433:5433
  #   healthcheck:
  #       test: ["CMD", "yb-ts-cli", "--server_address=localhost", "is_server_ready"]
  #       interval: 10s
  #       timeout: 5s
  #       retries: 12
  
  # catalog-db-init:
  #   platform: linux/amd64
  #   image: rtdl/psql-client:latest
  #   container_name: rtdl_catalog-db-init
  #   volumes:
  #     - ./catalog/scripts/create-user-db.postgres.sql:/create-user-db.postgres.sql
  #   entrypoint: psql -h catalog-db -p 5433 -U yugabyte -f /create-user-db.postgres.sql
  #   deploy:
  #     restart_policy:
  #       condition: on-failure
  #       delay: 5s
  #       max_attempts: 5
  #       window: 10s
  #   depends_on:
  #     catalog-db:
  #       condition: service_healthy

  # catalog:
  #   platform: linux/amd64
  #   image: rtdl/hive-metastore
  #   container_name: rtdl_catalog-init
  #   expose:
  #     - 9083
  #   ports:
  #     - 9083:9083
  #   volumes:
  #     - ./catalog/scripts/entrypoint-init.sh:/entrypoint.sh
  #     - ./catalog/conf/metastore-site.ybdb.xml:/opt/apache-hive-metastore-3.1.2-bin/conf/metastore-site.xml
  #   entrypoint: sh -c "chown hive:hive /entrypoint.sh && chmod +x /entrypoint.sh && sh -c /entrypoint.sh"
  #   depends_on:
  #     catalog-db:
  #       condition: service_healthy
  #     catalog-db-init:
  #       condition: service_completed_successfully
  ### For YBDB - End ###

  ### For Postgres - Start ###
  catalog-db:
    platform: linux/amd64
    image: postgres:latest
    container_name: rtdl_catalog-db
    volumes:
      - ./storage/rtdl-catalog-db_data:/var/lib/postgresql/data
    expose:
      - 5432
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
        test: ["CMD-SHELL", "pg_isready -U postgres"]
        interval: 10s
        timeout: 5s
        retries: 12
  
  catalog-db-init:
    platform: linux/amd64
    image: rtdl/psql-client:latest
    container_name: rtdl_catalog-db-init
    volumes:
      - ./catalog/scripts/create-user-db.postgres.sql:/create-user-db.postgres.sql
    entrypoint: psql -h catalog-db -p 5432 -U postgres -f /create-user-db.postgres.sql
    environment:
      PGPASSWORD: postgres
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 5
        window: 10s
    depends_on:
      catalog-db:
        condition: service_healthy
  
  catalog:
    platform: linux/amd64
    image: rtdl/hive-metastore
    container_name: rtdl_catalog-init
    expose:
      - 9083
    ports:
      - 9083:9083
    volumes:
      - ./catalog/scripts/entrypoint-init.sh:/entrypoint.sh
      - ./catalog/conf/metastore-site.postgres.xml:/opt/apache-hive-metastore-3.1.2-bin/conf/metastore-site.xml
    user: root
    entrypoint: bash -c "chown hive:hive /entrypoint.sh && chmod +x /entrypoint.sh && bash -c /entrypoint.sh"
    depends_on:
      catalog-db:
        condition: service_healthy
      catalog-db-init:
        condition: service_completed_successfully
  ### For Postgres - End ###
  ##### Catalog Services - End #####
