version: '3'

services:
  yugabyte:
    image: yugabytedb/yugabyte:latest
    container_name: rtdl_yugabyte-hive-metastore
    volumes:
      - ./yb_data:/home/yugabyte/yb_data
    command: ["bin/yugabyted", "start", "--base_dir=/home/yugabyte/yb_data", "--daemon=false"]
    ports:
      - 7000:7000
      - 9000:9000
      - 5433:5433
      - 9042:9042
    healthcheck:
        test: ["CMD", "yb-ts-cli", "--server_address=localhost", "is_server_ready"]
        interval: 5s
        timeout: 3s
        retries: 10

  hive-metastore:
    build:
      context: ./hive-metastore
    image: hive-metastore:latest
    container_name: rtdl_hive-metastore
    ports:
    - 9083:9083
    depends_on:
      yugabyte:
        condition: service_healthy
    links:
      - yugabyte
