version: '3'

services:
  catalog-db:
    image: yugabytedb/yugabyte:latest
    container_name: rtdl_rtdl-catalog-db
    volumes:
      - ./catalog-db_data:/home/yugabyte/yb_data
    command: ["bin/yugabyted", "start", "--base_dir=/home/yugabyte/yb_data", "--daemon=false"]
    ports:
      - 7000:7000
      - 9000:9000
      - 5433:5433
      - 9042:9042
    healthcheck:
        test: ["CMD", "yb-ts-cli", "--server_address=localhost", "is_server_ready"]
        interval: 10s
        timeout: 5s
        retries: 12

  catalog-db-init:
    build:
      context: ./psql-client
    image: rtdl/psql-client:latest
    container_name: rtdl_rtdl-catalog-db-init
    volumes:
      - ./catalog/scripts/create-user.postgres.sql:/create-user.postgres.sql
    entrypoint: psql -h catalog-db -p 5433 -U yugabyte -f /create-user.postgres.sql
    depends_on:
      catalog-db:
        condition: service_healthy
    links:
      - catalog-db
